# Generated by Django 3.2 on 2022-07-07 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply_comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reply_comment',
            name='name',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Reply_comment',
        ),
    ]
